db:
  image: postgres:9.3
  ports:
    - "5432:5432"
  volumes:
    - ~/.docker-volumes/%%app_name%%/db:/var/lib/postgresql/data
web:
  build: . 
  volumes:
    - .:%%app_home%%
  ports:
    - "3000:3000"
  links:
    - db
